### ISSUE TITLE
Specified folder doesn't sync

### ISSUE THREAD

**Issue by holgersprute** [ktheod/OneDriveBully#5]
Dear ktheod,

I had no problem installing your software, chose the OneDrive root folder and added the symbolic link to the sub-folder of my "Documents" folder, that I was looking to sync.

However, even after triggering with "Bully now", the folder is not uploaded/synced. The status of the folder remains in "sync pending". This is what I had, before installing your program.

Any idea what might be the issue? What info can I give to you that might help to determine the problem?

Thanks,
JHS

**Comment by ktheod** [comment]
Hi holgersprute, 

sorry for the long delay. Can you contact me on Facebook messenger and send me a screenshot of your Settings Form? Please mask if possible your username or any other private/sensitive information.

Thanks,

**Comment by holgersprute** [comment]
Hi ktheod,

I'm an old dude, no Facebook. Any other way to contact you. Is this email address OK?

Holger

On April 12, 2019 4:54:02 AM GMT+08:00, KTheodoridis <notifications@github.com> wrote:
>Hi holgersprute, 
>
>sorry for the long delay. Can you contact me on Facebook messenger and
>send me a screenshot of your Settings Form? Please mask if possible
>your username or any other private/sensitive information.
>
>Thanks,
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ktheod/OneDriveBully/issues/5#issuecomment-482309920

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ktheod** [comment]
Hi holgersprute,

sorry again for the long delay. One thing I have noticed from other users feedback is that Windows user folders are synced kind of differently by OneDrive. Please check in your OneDrive settings that you are syncing these folders/subfolders and since these are on your main drive there is no need for symbolic links. 

Also please update to v1.3 (if your are still using OneDrive Bully).

Thanks,
